### ISSUE TITLE
Script to convert files from one format to another

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#111]
Hi Raudius!

I am trying to reuse the [unoconv web-service](https://github.com/zrrrzzt/docker-unoconv-webservice) in docker for the file format conversion.

I have created the script to pick a file, a format to convert to, and the filename to save to (optional). By default, it converts to PDF. The script produces 0 kB, unfortunately.

Would you be so kind to help to find what is not working with this script:

```
local input_file = get_input_files()[1] 

local dir = get_input("output_location")
local output_name = get_input("file_name")
local output_format = get_input("convert_to")

-- if (type(output_format) ~= "table" or #output_format == 0) then
--    output_format = { "pdf" }
-- end

if (output_name == nil or output_name == "") then
  	output_name = input_file.name .. "." .. output_format
end
  
-- if (string.find(output_name, ".pdf") == nil) then
--	output_name = output_name .. ".pdf"
-- end

output_file = new_file(dir, output_name)

 -- TODO: check the file creation failed (output_file == nil) and abort if necessary 

input_path = meta_data(input_file).local_path
output_path = meta_data(output_file).local_path

--  curl --form file=@test.docx http://localhost:3000/unoconv/pdf > test.pdf
command_tpl = "curl --form file=@%s http://localhost:3000/unoconv/%s > %s"
command = command_tpl:format(input_path, output_format, output_path)

result = shell_command(command)
-- TODO: handle result
```  

Thanks a lot!

**Comment by Raudius** [comment]
Judging from your updates looks like you have it all working?

Let me know if you have any other questions

**Comment by ostasevych** [comment]
> Judging from your updates looks like you have it all working?
> 
> Let me know if you have any other questions

Ah, yeah, one more struggle: I found that if unoconv results in error it is completely locked and other actions are not possible, so had to manually unlock it.

This happens in case, if the conversion fails. Eg, if I try to convert from PDF to TXT the script crashes:

```
$ unoconv -f txt new.pdf
/usr/bin/unoconv:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1037, in convert
    document.storeToURL(outputurl, tuple(outputprops) )
uno.com.sun.star.io.IOException: SfxBaseModel::impl_store <file:///home/server/Documents/test/new.txt> failed: 0xc10(Error Area:Io Class:Write Code:16) ./sfx2/source/doc/sfxbasemodel.cxx:3202 ./sfx2/source/doc/sfxbasemodel.cxx:1775

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/unoconv", line 1282, in <module>
    main()
  File "/usr/bin/unoconv", line 1198, in main
    convertor.convert(inputfn)
  File "/usr/bin/unoconv", line 1039, in convert
    raise UnoException("Unable to store document to %s (ErrCode %d)\n\nProperties: %s" % (outputurl, e.ErrCode, outputprops), None)
  File "/usr/lib/python3/dist-packages/uno.py", line 505, in _uno_struct__getattr__
    return getattr(self.__dict__["value"], name)
AttributeError: ErrCode
```

So, it is locked

```
$ ~/Documents/test$ ps aux | grep libre
server    968221 23.0  1.1 736812 179400 pts/5   Sl   18:54   0:03 /usr/lib/libreoffice/program/soffice.bin --headless --invisible --nocrashreport --nodefault --nofirststartwizard --nologo --norestore --accept=socket,host=127.0.0.1,port=2002,tcpNoDelay=1;urp;StarOffice.ComponentContext
```

Here are two thoughts:
1. How to analyse that the command returned good value?
2. I was thinking to use a workaround, eg
```
if (input_file.name:match("^.+(%..+)$") == "pdf" and output_format == "txt") then
   output_format = "odt"
end
```
but that is not a good solution, I think, so
3. I was thinking to use iterative conversion, so first from PDF to ODT, and afterwards from ODT to TXT. The idea was to reuse the command ``` unoconv -f txt `unoconv -f odt file.pdf` ```. However it fails, leading to the error:

```
unoconv: RuntimeException during import phase:
Office probably died. Unsupported URL <file.pdf>: "type detection failed" ./framework/source/loadenv/loadenv.cxx:189
/usr/bin/unoconv:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import LooseVersion
unoconv: you have to provide a filename or url as argument
Try `unoconv -h' for more information.
```

Perhaps, you may suggest something?
