### ISSUE TITLE
Issues after upgrading NC to 28.0.5

### ISSUE THREAD

**Issue by ostasevych** [Raudius/files_scripts#163]
Hi! I have upgraded my NC instance from 27.1.x to the recent one 28.0.5 and started to get errors when trying to use the files_script for converting files from one format to another, getting the error:

```
OCA\FilesScripts\Interpreter\RegistrableFunction::getPath(): Argument #1 ($data) must be of type array, null given, called in /www/html/nextcloud/apps/files_scripts/lib/Interpreter/Functions/Files/New_File.php on line 17
```

Eg, full error log for 2 conversions (xlsx an png files)
```
{"reqId":"************","level":3,"time":"2024-04-30T16:58:14+03:00","remoteAddr":"***.***.***.***","user":"myuser","app":"files_scripts","method":"POST","url":"/apps/files_scripts/run/6","message":"File scripts runtime error","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","version":"28.0.5.1","data":{"app":"files_scripts","error_message":"OCA\\FilesScripts\\Interpreter\\RegistrableFunction::getPath(): Argument #1 ($data) must be of type array, null given, called in /www/html/nextcloud/apps/files_scripts/lib/Interpreter/Functions/Files/New_File.php on line 17","trace":"#0 /www/html/nextcloud/apps/files_scripts/lib/Interpreter/Lua/LuaInterpreter.php(14): Lua->eval()\n#1 /www/html/nextcloud/apps/files_scripts/lib/Interpreter/Interpreter.php(32): OCA\\FilesScripts\\Interpreter\\Lua\\LuaInterpreter->eval()\n#2 /www/html/nextcloud/apps/files_scripts/lib/Service/ScriptService.php(88): OCA\\FilesScripts\\Interpreter\\Interpreter->execute()\n#3 /www/html/nextcloud/apps/files_scripts/lib/Controller/ScriptController.php(204): OCA\\FilesScripts\\Service\\ScriptService->runScript()\n#4 www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\FilesScripts\\Controller\\ScriptController->run()\n#5/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController()\n#6 /www/html/nextcloud/lib/private/AppFramework/App.php(184): OC\\AppFramework\\Http\\Dispatcher->dispatch()\n#7 /www/html/nextcloud/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main()\n#8 /www/html/nextcloud/lib/base.php(1069): OC\\Route\\Router->match()\n#9 /www/html/nextcloud/index.php(39): OC::handleRequest()\n#10 {main}","script_id":"6","inputs":"[{\"[object] (OCA\\FilesScripts\\Db\\ScriptInput)\":{\"id\":182,\"OCP\\AppFramework\\Db\\Entity_updatedFields\":[],\"OCP\\AppFramework\\Db\\Entity_fieldTypes\":{\"id\":\"integer\"},\"*name\":\"input_file\",\"*description\":\"File to conver (selected)\",\"*scriptId\":6,\"*options\":\"{\\\"type\\\":\\\"filepick\\\",\\\"multiselectOptions\\\":[],\\\"filepickMimes\\\":[\\\"image\\/png\\\",\\\"image\\/jpeg\\\",\\\"application\\/pdf\\\",\\\"application\\/vnd.ms-powerpoint\\\",\\\"application\\/vnd.openxmlformats-officedocument.presentationml.presentation\\\",\\\"image\\/svg+xml\\\",\\\"\\tapplication\\/msword\\\",\\\"application\\/vnd.openxmlformats-officedocument.wordprocessingml.document\\\",\\\"text\\/csv\\\",\\\"application\\/vnd.oasis.opendocument.presentation\\\",\\\"application\\/vnd.oasis.opendocument.spreadsheet\\\",\\\"application\\/vnd.oasis.opendocument.text\\\",\\\"application\\/rtf\\\",\\\"image\\/tiff\\\",\\\"application\\/vnd.ms-excel\\\",\\\"application\\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\\\",\\\"text\\/html\\\"],\\\"allowMultiple\\\":false,\\\"textarea\\\":false}\",\"*value\":\"\"}},{\"[object] (OCA\\FilesScripts\\Db\\ScriptInput)\":{\"id\":183,\"OCP\\AppFramework\\Db\\Entity_updatedFields\":[],\"OCP\\AppFramework\\Db\\Entity_fieldTypes\":{\"id\":\"integer\"},\"*name\":\"output_location\",\"*description\":\"Place to store\",\"*scriptId\":6,\"*options\":\"{\\\"type\\\":\\\"filepick\\\",\\\"multiselectOptions\\\":[],\\\"filepickMimes\\\":[\\\"httpd\\/unix-directory\\\"],\\\"allowMultiple\\\":false,\\\"textarea\\\":false}\",\"*value\":\"\"}},{\"[object] (OCA\\FilesScripts\\Db\\ScriptInput)\":{\"id\":184,\"OCP\\AppFramework\\Db\\Entity_updatedFields\":[],\"OCP\\AppFramework\\Db\\Entity_fieldTypes\":{\"id\":\"integer\"},\"*name\":\"convert_to\",\"*description\":\"Convert to format (default PDF)\",\"*scriptId\":6,\"*options\":\"{\\\"type\\\":\\\"multiselect\\\",\\\"multiselectOptions\\\":[\\\"pdf\\\",\\\"docx\\\",\\\"xlsx\\\",\\\"csv\\\",\\\"pptx\\\",\\\"odt\\\",\\\"ods\\\",\\\"odp\\\",\\\"jpg\\\",\\\"png\\\",\\\"html\\\",\\\"txt\\\",\\\"doc\\\",\\\"xls\\\",\\\"ppt\\\",\\\"tiff\\\",\\\"rtf\\\",\\\"svg\\\",\\\"md\\\"],\\\"filepickMimes\\\":[],\\\"allowMultiple\\\":false,\\\"textarea\\\":false}\",\"*value\":\"\"}}]","files":"{\"1\":\"/myuser/files/groupname/myfile.xlsx\"}"},"id":"**************"}
```

```
{"reqId":"******","level":3,"time":"2024-04-30T17:00:56+03:00","remoteAddr":"***.***.***.***","user":"myuser","app":"files_scripts","method":"POST","url":"/apps/files_scripts/run/6","message":"File scripts runtime error","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36","version":"28.0.5.1","data":{"app":"files_scripts","error_message":"OCA\\FilesScripts\\Interpreter\\RegistrableFunction::getPath(): Argument #1 ($data) must be of type array, null given, called in /www/html/nextcloud/apps/files_scripts/lib/Interpreter/Functions/Files/New_File.php on line 17","trace":"#0 /www/html/nextcloud/apps/files_scripts/lib/Interpreter/Lua/LuaInterpreter.php(14): Lua->eval()\n#1 /www/html/nextcloud/apps/files_scripts/lib/Interpreter/Interpreter.php(32): OCA\\FilesScripts\\Interpreter\\Lua\\LuaInterpreter->eval()\n#2 /www/html/nextcloud/apps/files_scripts/lib/Service/ScriptService.php(88): OCA\\FilesScripts\\Interpreter\\Interpreter->execute()\n#3 /www/html/nextcloud/apps/files_scripts/lib/Controller/ScriptController.php(204): OCA\\FilesScripts\\Service\\ScriptService->runScript()\n#4 /www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(230): OCA\\FilesScripts\\Controller\\ScriptController->run()\n#5/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(137): OC\\AppFramework\\Http\\Dispatcher->executeController()\n#6 /www/html/nextcloud/lib/private/AppFramework/App.php(184): OC\\AppFramework\\Http\\Dispatcher->dispatch()\n#7 /www/html/nextcloud/lib/private/Route/Router.php(315): OC\\AppFramework\\App::main()\n#8 /www/html/nextcloud/lib/base.php(1069): OC\\Route\\Router->match()\n#9 /www/html/nextcloud/index.php(39): OC::handleRequest()\n#10 {main}","script_id":"6","inputs":"[{\"[object] (OCA\\FilesScripts\\Db\\ScriptInput)\":{\"id\":182,\"OCP\\AppFramework\\Db\\Entity_updatedFields\":[],\"OCP\\AppFramework\\Db\\Entity_fieldTypes\":{\"id\":\"integer\"},\"*name\":\"input_file\",\"*description\":\"File to convert (selected)\",\"*scriptId\":6,\"*options\":\"{\\\"type\\\":\\\"filepick\\\",\\\"multiselectOptions\\\":[],\\\"filepickMimes\\\":[\\\"image\\/png\\\",\\\"image\\/jpeg\\\",\\\"application\\/pdf\\\",\\\"application\\/vnd.ms-powerpoint\\\",\\\"application\\/vnd.openxmlformats-officedocument.presentationml.presentation\\\",\\\"image\\/svg+xml\\\",\\\"\\tapplication\\/msword\\\",\\\"application\\/vnd.openxmlformats-officedocument.wordprocessingml.document\\\",\\\"text\\/csv\\\",\\\"application\\/vnd.oasis.opendocument.presentation\\\",\\\"application\\/vnd.oasis.opendocument.spreadsheet\\\",\\\"application\\/vnd.oasis.opendocument.text\\\",\\\"application\\/rtf\\\",\\\"image\\/tiff\\\",\\\"application\\/vnd.ms-excel\\\",\\\"application\\/vnd.openxmlformats-officedocument.spreadsheetml.sheet\\\",\\\"text\\/html\\\"],\\\"allowMultiple\\\":false,\\\"textarea\\\":false}\",\"*value\":\"\"}},{\"[object] (OCA\\FilesScripts\\Db\\ScriptInput)\":{\"id\":183,\"OCP\\AppFramework\\Db\\Entity_updatedFields\":[],\"OCP\\AppFramework\\Db\\Entity_fieldTypes\":{\"id\":\"integer\"},\"*name\":\"output_location\",\"*description\":\"Place to store\",\"*scriptId\":6,\"*options\":\"{\\\"type\\\":\\\"filepick\\\",\\\"multiselectOptions\\\":[],\\\"filepickMimes\\\":[\\\"httpd\\/unix-directory\\\"],\\\"allowMultiple\\\":false,\\\"textarea\\\":false}\",\"*value\":\"\"}},{\"[object] (OCA\\FilesScripts\\Db\\ScriptInput)\":{\"id\":184,\"OCP\\AppFramework\\Db\\Entity_updatedFields\":[],\"OCP\\AppFramework\\Db\\Entity_fieldTypes\":{\"id\":\"integer\"},\"*name\":\"convert_to\",\"*description\":\"Convert to PDF (default)\",\"*scriptId\":6,\"*options\":\"{\\\"type\\\":\\\"multiselect\\\",\\\"multiselectOptions\\\":[\\\"pdf\\\",\\\"docx\\\",\\\"xlsx\\\",\\\"csv\\\",\\\"pptx\\\",\\\"odt\\\",\\\"ods\\\",\\\"odp\\\",\\\"jpg\\\",\\\"png\\\",\\\"html\\\",\\\"txt\\\",\\\"doc\\\",\\\"xls\\\",\\\"ppt\\\",\\\"tiff\\\",\\\"rtf\\\",\\\"svg\\\",\\\"md\\\"],\\\"filepickMimes\\\":[],\\\"allowMultiple\\\":false,\\\"textarea\\\":false}\",\"*value\":\"\"}}]","files":"{\"1\":\"/myuser/files/Documents/file.png\"}"},"id":"":"**************"}
```

Here is the 17 line `$ cat -n /www/nextcloud/apps/files_scripts/lib/Interpreter/Functions/Files/New_File.php`:
```
 <?php
     2
     3  namespace OCA\FilesScripts\Interpreter\Functions\Files;
     4
     5  use OCA\FilesScripts\Interpreter\RegistrableFunction;
     6  use OCP\Files\Folder;
     7  use OCP\Files\NotPermittedException;
     8
     9  /**
    10   * `new_file(Node folder, String name, [String content]=nil): Node|nil`
    11   *
    12   * Creates a new file in the specified folder.
    13   * If successful, returns the newly created file node. If file creation fails, returns `nil`.
    14   */
    15  class New_File extends RegistrableFunction {
    16          public function run($node = null, $name = null, $content = null): ?array {
    17                  $folder = $this->getNode($this->getPath($node));
    18                  if (false === $folder instanceof Folder || !$name) {
    19                          return null;
    20                  }
    21
    22                  try {
    23                          $file = $folder->newFile($name, $content);
    24                          return $this->getNodeData($file);
    25                  } catch (NotPermittedException $e) {
    26                          return null;
    27                  }
    28          }
    29  }
```

What may be wrong there?

**Comment by ostasevych** [comment]
@Raudius Hi! Are any chances to fix the issue?

**Comment by ostasevych** [comment]
UPD: If I try to select the folder where to save the resulting file after converting the script gives error: `FilePicker: No nodes selected`. 

As I understand that after update to v28 the algorithm to define the default folder changed and I have to indicate it manually. 

In my script I have:
```
local dir = get_input("output_location")
```

What I have to change?
